site_name: Generative AI Study Hub
site_url: https://baskarm.github.io/generative-ai-study-hub/

theme:
  name: material
  logo: images/adhana.png
  custom_dir: docs/partials

  font:
    text: Inter
    code: Fira Code

  palette:
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - content.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - content.action.edit

docs_dir: docs

nav:
  - Home: index.md
  - Python: study-path/1-python/index.md
  - Statistics: study-path/2-statistics/index.md
  - DS & ML : study-path/3-datascience-machine-learning/index.md
  - Transformers & Gen AI: study-path/4-transformers-generative-ai/index.md
  - RAG + LangChain: study-path/5-rag-langchain/index.md
  - LLM Ops: study-path/6-llmops/index.md
  - AI Evaluation: study-path/7-ai-eval-engineering/index.md
  - Reference Hub:
      - Overview: reference-hub/index.md
      - Foundation:
          - NLP Overview: reference-hub/foundation/nlp-overview.md
          - Transformers: reference-hub/foundation/transformers.md
          - Models: reference-hub/foundation/models.md
      - Practice:
          - Tokenization: reference-hub/practice/tokenization.md
          - Embeddings: reference-hub/practice/embeddings.md
          - Fine Tuning: reference-hub/practice/fine-tuning.md
          - Efficiency: reference-hub/practice/efficiency.md
      - Applications:
          - Semantic Search: reference-hub/applications/semantic-search.md
          - QA from Docs: reference-hub/applications/qa-over-docs.md
          - Instruction Tuning: reference-hub/applications/instruction-tuning.md
      - LLMs:
          - Introduction: reference-hub/llms/intro.md
          - RLHF: reference-hub/llms/rlhf.md
          - Scaling: reference-hub/llms/scaling.md
      - Knowledge:
          - Prompt Engineering: reference-hub/knowledge/prompt-engineering.md
          - Hugging Face: reference-hub/knowledge/huggingface.md
          - Research Notes: reference-hub/knowledge/research.md
          - Tools & Libraries: reference-hub/knowledge/tools.md
          - Learning Links: reference-hub/knowledge/learning-links.md

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: false
      locale: en

extra_css:
  - styles/logo.css

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/...

extra_javascript:
  - /generative-ai-study-hub/service-worker.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - toc
  - admonition