site_name: Generative AI Study Hub
site_url: https://baskarm.github.io/generative-ai-study-hub/

theme:
  name: material

docs_dir: docs

nav:
  - Home: index.md
  - Study Path:
      - Transformers & Generative AI:
          - 01 - Intro: study-path/transformers/01-intro.md
          - 02 - Getting Started: study-path/transformers/02-getting-started.md
          - 03 - NLP Overview: study-path/transformers/03-nlp-overview.md
          - 04 - Transformer Intro: study-path/transformers/04-transformer-intro.md
          - 05 - Projects & Prompting: study-path/transformers/05-projects-prompting.md
          - 06 - Using Transformers (Practical): study-path/transformers/06-using-transformers.md
          - 07 - Reasoning with LLMs: study-path/transformers/07-reasoning.md
          - 08 - Intro to LLMs: study-path/transformers/08-llm-intro.md
          - 09 - Preparing LLMs: study-path/transformers/09-llm-prep.md
          - 10 - Advanced LLM Training: study-path/transformers/10-llm-advanced.md
          - 11 - Specialized LLM Training: study-path/transformers/11-llm-specialized.md
          - 12 - Final Deployment: study-path/transformers/12-llm-deployment.md
      - LLM Ops:
          - 01 - Getting Started: study-path/llmops/01-getting-started.md
          - 02 - Pre-Deployment Strategies: study-path/llmops/02-pre-deployment.md
          - 03 - MLOps Foundations: study-path/llmops/03-mlops-foundations.md
          - 04 - Advanced Model Deployment: study-path/llmops/04-advanced-deployment.md
          - 05 - ML Inference Optimization: study-path/llmops/05-inference-optimization.md
          - 06 - Economics of Inference: study-path/llmops/06-economics.md
          - 07 - Cluster Management: study-path/llmops/07-cluster-management.md
          - 08 - Real-Time API Deployment: study-path/llmops/08-real-time-api.md
  - Reference Hub:
      - Foundation:
          - NLP Overview: reference-hub/foundation/nlp-overview.md
          - Transformers: reference-hub/foundation/transformers.md
          - Models: reference-hub/foundation/models.md
      - Practice:
          - Tokenization: reference-hub/practice/tokenization.md
          - Embeddings: reference-hub/practice/embeddings.md
          - Fine Tuning: reference-hub/practice/fine-tuning.md
          - Efficiency: reference-hub/practice/efficiency.md
      - Applications:
          - Semantic Search: reference-hub/applications/semantic-search.md
          - QA from Docs: reference-hub/applications/qa-over-docs.md
          - Instruction Tuning: reference-hub/applications/instruction-tuning.md
      - LLMs:
          - Introduction: reference-hub/llms/intro.md
          - RLHF: reference-hub/llms/rlhf.md
          - Scaling: reference-hub/llms/scaling.md
      - Knowledge:
          - Prompt Engineering: reference-hub/knowledge/prompt-engineering.md
          - Hugging Face: reference-hub/knowledge/huggingface.md
          - Research Notes: reference-hub/knowledge/research.md
          - Tools & Libraries: reference-hub/knowledge/tools.md
          - Learning Links: reference-hub/knowledge/learning-links.md